spring.profiles.active=local
spring.application.name=cloudcost

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=db_username
spring.datasource.password=db_password
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate/JPA Database Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Apache Kafka Settings
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=finops-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# 4. Turn on Automation Scheduling on your laptop
spring.main.allow-bean-definition-overriding=true

spring.ai.google.api-key=your_api_key

# 6. Automated Email Notification Gateway Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_gmail_address@gmail.com
spring.mail.password=app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
